### ISSUE TITLE
Set GitHub token from code

### ISSUE THREAD

**Issue by luigigargioni** [electron-delta/electron-delta#5]
How can I set the GitHub token from code to access the list of my private repositories?
Right now I have to set the GH_TOKEN environment variable from PowerShell.

`[Environment]::SetEnvironmentVariable("GH_TOKEN","<GitHub_token>","User")`

To upload the build I can specify it in the JSON and it works, but to access the list of previous versions, in my case from a private repository, I do not know how to set it from code.

Thanks

**Comment by sandeep1995** [comment]
You can use https://github.com/motdotla/dotenv for the script fetching previous versions.

1. Create a `.env` file at the root of your project:
```sh
GH_TOKEN=
```
2. Add the `.env` file in the gitignore
3. Simple call the following at the top of the code for fetching previous releases
```js
require('dotenv').config();
// rest of the code
```
